root = "."
tmp_dir = "tmp"

[build]
# 如果你是mac 使用bin 下面的 main.exe 去掉 .exe 
cmd = "go build -o ./tmp/main ./cmd/main.go"
# 如果你是mac 使用bin 即可 注释掉full_bin
bin = "./tmp/main"
env_files = ["./config/config.yaml"]
env = ["AUTO_MIGRATE=true"]
# windows11 使用full_bin 会报错 详情看 issue https://github.com/air-verse/air/issues/659
# full_bin = "D:\\code-work\\carline-go\\luck-go\\tmp\\main.exe"
log = "air_errors.log"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor"]
delay = 1000                                # ms

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[log]
time = true
level = "info"

[misc]
clean_on_exit = false
