server:
  port: 7001
  mode: debug

# database:
#   driver: mysql
#   host: localhost
#   port: 3306
#   username: root
#   password: password
#   dbname: myapp

# redis:
#   host: localhost
#   port: 6379
#   password: ""
