server:
  port: 7001
  mode: debug

database:
  driver: mysql
  host: rm-bp1riq19yolb58kecho.mysql.rds.aliyuncs.com
  port: 3306
  username: carline
  password: xxxx
  dbname: test_cn
# redis:
#   host: localhost
#   port: 6379
#   password: ""
